### ISSUE TITLE
работае

### ISSUE THREAD

**Issue by pitther** [pawajka/web-design#1]
**робе**

**Comment by pawajka** [comment]
Доброго дня! Дякую за відгук!

**Comment by pitther** [comment]
дуже подобається ваша странічка. чекаю оновлення 👍🏻 . бажаю здоров'я!

**Comment by pitther** [comment]
**[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq[eq [eq**

**Comment by pawajka** [comment]
ОБНОВИВ ЧЕКАЙ АМАТЬ

**Comment by pawajka** [comment]
виключить адблока там реклама

**Comment by pitther** [comment]
**хуйня**  не робе !

**Comment by pitther** [comment]
адблок нашо

**Comment by pitther** [comment]
я рекламу не дивнлюс б

**Comment by pawajka** [comment]
там капчя

**Comment by pitther** [comment]
.--._.--.
          ( O     O )
          /   . .   \
         .`._______.'.
        /(           )\
      _/  \  \   /  /  \_
   .~   `  \  \ /  /  '   ~.
  {    -.   \  V  /   .-    }
_ _`.    \  |  |  |  /    .'_ _
>_       _} |  |  | {_       _<
 /. - ~ ,_-'  .^.  `-_, ~ - .\
         '-'|/   \|`-`

**Comment by pitther** [comment]
a'!   _,,_ a'!   _,,_     a'!   _,,_
  \\_/    \  \\_/    \      \\_/    \.-,
   \, /-( /'-,\, /-( /'-,    \, /-( /
   //\ //\\   //\ //\\       //\ //\\jrei

**Comment by pitther** [comment]
```    .--' |
   /___^ |     .--.
       ) |    /    \
      /  |  /`      '.
     |   '-'    /     \
     \         |      |\
      \    /   \      /\|
       \  /'----`\   /
       |||       \\ |
       ((|        ((|
       |||        |||
jgs   //_(       //_( ```

**Comment by pitther** [comment]
```
       ____  __.---""---.__  ____
      /####\/              \/####\
     (   /\ )              ( /\   )
     \____/                \____/
    __/                          \__
 .-"    .                      .    "-.
 |  |   \.._                _../   |  |
  \  \    \."-.__________.-"./    /  /
    \  \    "--.________.--"    /  /
  ___\  \_                    _/  /___
./    )))))                  (((((    \.
\                                      /
 \           \_          _/           /
   \    \____/""-.____.-""\____/    /
     \    \                  /    /
      \.  .|                |.  ./
    ." / |  \              /  | \  ".
 ."  /   |   \            /   |   \   ".
/.-./.--.|.--.\          /.--.|.--.\.-.|

```

**Comment by pitther** [comment]
по плотному коммиту и на атбой  ==DDD

**Comment by pawajka** [comment]
_____________________________#####____
_________ Я знаю _____________#####____
___________что ты делал _______####______
_________прошлым летом!!________##________
_____________________________######_____
____________________________#######_____
____####__________________#########___
___######________________###_######___
#########_______________###__######__
_#######_______________###___######___
_______#################____######__
_______##########################__
________################____#####____
_________##___________##_____####______
_________##___________##_____#########___
_______###__________###______#########__

**Comment by pawajka** [comment]
`_____________________________#####____
_________ Я знаю _____________#####____
___________что ты делал _______####______
_________прошлым летом!!________##________
_____________________________######_____
____________________________#######_____
____####__________________#########___
___######________________###_######___
#########_______________###__######__
_#######_______________###___######___
_______#################____######__
_______##########################__
________################____#####____
_________##___________##_____####______
_________##___________##_____#########___
_______###__________###______#########__
`

**Comment by pawajka** [comment]
...............00000000
...............00000000000
..............00,,,,,,,0,,,,,,00
.............0,,,,,,,,,0,,,,,,,,,0
............0,,,,,,,,,,0,,,,,,,,,,0
...........0,,,,,,,,,,,0,,,,,,,,,,,0
...........0,,,,,,,,,,,,,,,,,,,,,,,,0
...........0,,,,,,,,,,,,,,,,,,,,,,,,0
...........0,,,,,,,,,,,,,,,,,,,,,,,,0
............0,,,,,,,,,,,,,,,,,,,,,0
.............000000000000000
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.........000,,,,,,,,,,,,,,,,,,,,,,000
.......00,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,00
......0,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
.....0,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
....0,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
...0,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
...0,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
...0,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
....0,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
.....0,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,0

**Comment by pitther** [comment]
[Ты не сможешь сделать такой статус ! | ВКонтактеhttps://vk.com › club84868980](https://vk.com/club84868980)
Ты не сможешь сделать такой статус ! · · · · · · ДѺЂҎѺ ПѺӁӐԒѺßӐҬЬ· · · · · ·. Информация. прикольные статусы.

[Ник ТЫ НЕ СМОЖЕШЬ СДЕЛАТЬ СЕБЕ ТАКОЙ СТАТУС ...https://socialnick.ru › nick](https://socialnick.ru/nick/4761)
Ник ТЫ НЕ СМОЖЕШЬ СДЕЛАТЬ СЕБЕ ТАКОЙ СТАТУС!!!! автоматически оформлен как ඏϮЫ НЕ СМОЖΞШႱ☆ҪДΞɅÃᏆЬ ᏨΞѢΞ☆ᏆÁҜОЙ ҪТǞᏆУᏨ!!!!ඏ для социальных сетей.

[Спам комментариями на ютубе - Форум – YouTube - Google ...https://support.google.com › youtube › thread › Спам-ко...](https://support.google.com/youtube/thread/80831063/%D0%A1%D0%BF%D0%B0%D0%BC-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D1%8F%D0%BC%D0%B8-%D0%BD%D0%B0-%D1%8E%D1%82%D1%83%D0%B1%D0%B5?hl=ru)
3 нояб. 2020 г. — 99% Ты |̳̿Н̳̿|е Сможешь Сделать |̳̿С̳̳̿е̳̳̿б̳̿||̳̿е̳̿| такой статус ··· он не копируется ·︻̿芫═━Это статус королей. Подробности.

**Comment by pawajka** [comment]
```
...............00000000
...............00000000000
..............00,,,,,,,0,,,,,,00
.............0,,,,,,,,,0,,,,,,,,,0
............0,,,,,,,,,,0,,,,,,,,,,0
...........0,,,,,,,,,,,0,,,,,,,,,,,0
...........0,,,,,,,,,,,,,,,,,,,,,,,,0
...........0,,,,,,,,,,,,,,,,,,,,,,,,0
...........0,,,,,,,,,,,,,,,,,,,,,,,,0
............0,,,,,,,,,,,,,,,,,,,,,0
.............000000000000000
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.............0,,,,,,,,,,,,,,,,,,,0
.........000,,,,,,,,,,,,,,,,,,,,,,000
.......00,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,00
......0,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
.....0,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
....0,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
...0,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
...0,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
...0,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
....0,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,0
.....0,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,0

```

**Comment by pitther** [comment]
```
[bug]     /"*._         _
      .-*'`    `*-.._.-'/
    < * ))     ,       ( 
      `*-._`._(__.--*"`.\
```

**Comment by pitther** [comment]
```
                                            .      //
                                       /) \ |\    //
  VK                             (\\|  || \)u|   |F     /)
                                  \```.FF  \  \  |J   .'/
                               __  `.  `|   \  `-'J .'.'
        ______           __.--'  `-. \_ J    >.   `'.'   .
    _.-'      ""`-------'           `-.`.`. / )>.  /.' .<'
  .'                                   `-._>--' )\ `--''
  F .                                          ('.--'"
 (_/                                            '\
  \                                             'o`.
  |\                                                `.
  J \          |              /      |                \
   L \                       J       (             .  |
   J  \      .               F        _.--'`._  /`. \_)
    F  `.    |                       /        ""   "'
    F   /\   |_          ___|   `-_.'
   /   /  F  J `--.___.-'   F  - /
  /    F  |   L            J    /|
 (_   F   |   L            F  .'||
  L  F    |   |           |  /J  |
  | J     `.  |           | J  | |              ____.---.__
  |_|______ \  L          | F__|_|___.---------'
--'        `-`--`--.___.-'-'---
```

**Comment by pawajka** [comment]
⣿⣿⣿⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ 
⣿⣿⣿⣵⣿⣿⣿⠿⡟⣛⣧⣿⣯⣿⣝⡻⢿⣿⣿⣿⣿⣿⣿⣿ 
⣿⣿⣿⣿⣿⠋⠁⣴⣶⣿⣿⣿⣿⣿⣿⣿⣦⣍⢿⣿⣿⣿⣿⣿ 
⣿⣿⣿⣿⢷⠄⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣏⢼⣿⣿⣿⣿ 
⢹⣿⣿⢻⠎⠔⣛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⣿⣿⣿⣿ 
⢸⣿⣿⠇⡶⠄⣿⣿⠿⠟⡛⠛⠻⣿⡿⠿⠿⣿⣗⢣⣿⣿⣿⣿ 
⠐⣿⣿⡿⣷⣾⣿⣿⣿⣾⣶⣶⣶⣿⣁⣔⣤⣀⣼⢲⣿⣿⣿⣿ 
⠄⣿⣿⣿⣿⣾⣟⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⢟⣾⣿⣿⣿⣿ 
⠄⣟⣿⣿⣿⡷⣿⣿⣿⣿⣿⣮⣽⠛⢻⣽⣿⡇⣾⣿⣿⣿⣿⣿ 
⠄⢻⣿⣿⣿⡷⠻⢻⡻⣯⣝⢿⣟⣛⣛⣛⠝⢻⣿⣿⣿⣿⣿⣿ 
⠄⠸⣿⣿⡟⣹⣦⠄⠋⠻⢿⣶⣶⣶⡾⠃⡂⢾⣿⣿⣿⣿⣿⣿ 
⠄⠄⠟⠋⠄⢻⣿⣧⣲⡀⡀⠄⠉⠱⣠⣾⡇⠄⠉⠛⢿⣿⣿⣿
 ⠄⠄⠄⠄⠄⠈⣿⣿⣿⣷⣿⣿⢾⣾⣿⣿⣇⠄⠄⠄⠄⠄⠉⠉ 
 ⠄⠄⠄⠄⠄⠄⠸⣿⣿⠟⠃⠄⠄⢈⣻⣿⣿⠄⠄⠄⠄⠄⠄⠄ 
 ⠄⠄⠄⠄⠄⠄⠄⢿⣿⣾⣷⡄⠄⢾⣿⣿⣿⡄⠄⠄⠄⠄⠄⠄ 
 ⠄⠄⠄⠄⠄⠄⠄⠸⣿⣿⣿⠃⠄⠈⢿⣿⣿⠄⠄⠄⠄⠄⠄⠄

**Comment by pitther** [comment]
![image](https://user-images.githubusercontent.com/26699314/170847876-77537d33-2bf3-40c2-afe1-97bfa045c38b.png)

**Comment by pitther** [comment]
![image](https://user-images.githubusercontent.com/26699314/170847888-96930eab-bffc-4c84-9910-e077d2182910.png)

**Comment by pawajka** [comment]
афігеть

**Comment by pawajka** [comment]
роз пічатай

**Comment by pitther** [comment]
![image](https://user-images.githubusercontent.com/26699314/170847906-5710328f-083c-4f7d-8533-6e57bd3a9105.png)

**Comment by pitther** [comment]
![image](https://user-images.githubusercontent.com/26699314/170847925-6efa307f-d3ae-4ce7-bd63-6eb27a0104d3.png)
![image](https://user-images.githubusercontent.com/26699314/170847929-01ced9be-9c5a-4438-8920-87773ce88330.png)
![image](https://user-images.githubusercontent.com/26699314/170847936-1d826edf-5618-4ba7-bc69-064e8cc6619f.png)
